### ISSUE TITLE
Change mouse buttons and display notifications.

### ISSUE THREAD

**Issue by ghost** [DRKblade/polybar-warrior#1] opened 2021-03-11 06:45 UTC
I would like to change the way notifications are displayed so that it only shows the number of tasks to be done. I added 'task status: pending count' to the script.
It worked, the next step is to change the left mouse button to open the file where all the tasks are saved, ideally if it could be edited in VIM.
If it is possible ?

**Comment by quandangv** [comment] 2021-03-11 10:46
Assuming the path to the file you want to open is `~/.task/pending.data`, using termite and vi, you can open the file by running `termite -e "vi $HOME/.task/pending.data"`.
Putting that in the `click1` function and the module will open your file on every left mouse click.

**Comment by quandangv** [comment] 2021-03-11 15:37
Seems like the issue is resolved, I'm closing this.

**Closed as completed by quandangv** 2021-03-11 15:37 UTC
